IS_AUGMENTATION: True
IMAGE_SIZE: [3, 224, 224] 
BATCH_SIZE: 32
EPOCHS: 1
CLASSES: 3
WEIGHTS: 'imagenet'
LEARNING_RATE: 0.001
DEVICE: 'cuda'
PRETRAINED: True
FREEZE_ALL: True
FREEZE_TILL: None
SEED: 122
IN_FEATURES: 1408
METRIC_NAMES: ["loss", "accuracy", "precision", "recall", "f1_score", "mAP50", "mAP90"]
NUM_WORKERS: 0